### PR TITLE
Integration of Sherman-Morrison-Woodbury kernels into QMCkl

### PR DESCRIPTION
**Pull request by fmgjcoppens**
TODO:
- [x]  Provide and complete documentation
- [x] Complete Org-file

### CODE REVIEW

File: org/qmckl_sherman_morrison_woodbury.cpp [hunk 1]
```diff
@@ -0,0 +1,535 @@
...
+    }
+
+    // Denominator
+    double den = 1 + C[Updates_index[l] - 1];
+    if (std::fabs(den) < threshold()) {
+#ifdef DEBUG1
+      std::cerr << "Breakdown condition triggered at " << Updates_index[l]
+                << std::endl;
+#endif
+    }
```
Comment (fmgjcoppens) [inline org/qmckl_sherman_morrison_woodbury.cpp:83]: Make it a test that returns an error code: 
- If Det > 0, return 0
- If det too close to 0, return 1. Don't print error message.

File: org/qmckl_sherman_morrison_woodbury.cpp [hunk 2]
```diff
@@ -0,0 +1,535 @@
...
+
+#ifdef DEBUG2
+  showMatrix2(Slater_inv, Dim, Dim, "Slater_inv AFTER update");
+#endif
+  return true;
+}
+
+// Sherman Morrison, with J. Slagel splitting (caller function)
+// http://hdl.handle.net/10919/52966
+void sherman_morrison_splitting_caller(double *Slater_inv, unsigned int Dim, unsigned int N_updates,
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.cpp:287]: Swap the names between `sherman_morrison_splitting_caller` and `sherman_morrisson_splitting`.

Maybe call the internal `slagel_splitting` ?

Declare the internal one with `static` keyword.

File: org/qmckl_sherman_morrison_woodbury.cpp (hunk 1 above)
Comment (fmgjcoppens) [reply org/qmckl_sherman_morrison_woodbury.cpp:83]: void function changed to bool:
If denominator is too close to 0; return false
Otherwise; return true.

File: org/qmckl_sherman_morrison_woodbury.cpp (hunk 2 above)
Comment (fmgjcoppens) [reply org/qmckl_sherman_morrison_woodbury.cpp]: Done.

File: org/qmckl_sherman_morrison_woodbury.org [hunk 3]
```diff
@@ -0,0 +1,1775 @@
+#+TITLE: Sherman-Morrison-Woodbury
+#+SETUPFILE: ../tools/theme.setup
+#+INCLUDE: ../tools/lib.org
+
+Low- and high-level functions that use the Sherman-Morrison and
+ Woodbury matrix inversion formulas to update the inverse of a
+ non-singualr matrix
```
Comment (fmgjcoppens) [inline org/qmckl_sherman_morrison_woodbury.org:7]: non-singular

File: org/qmckl_sherman_morrison_woodbury.org [hunk 4]
```diff
@@ -0,0 +1,1775 @@
...
+  context = qmckl_context_create();
+
+  qmckl_exit_code rc;
+  #+end_src
+
+  
+* Helper Functions
+  
+Helper functions that are used by the Sherman-Morrison-Woodbury kernels. 
+These functions can only be used internally by higher level functions.
```
Comment (fmgjcoppens) [inline org/qmckl_sherman_morrison_woodbury.org:33]: Replace by Private helper functions

File: org/qmckl_sherman_morrison_woodbury.org [hunk 5]
```diff
@@ -0,0 +1,1775 @@
...
+   :FRetType: double precision
+   :END:
+
+   ~qmckl_slagel_splitting~ is used internally to apply a list of rank-1 updates while splitting an update if necessary.
+   In case of a split it applies the first half of the update while putting the second half in waiting queue to be applied at the end.
+  
+   For a given update $u_j$ we define a threshold value $\epsilon_j$, which is the minimum value of 
+   $1+v_j^TS^{-1}u_j$ for a non-singular matrix $S$. If $1+v_j^TS^{-1}u_j \geq \epsilon_j$, 
+   the update is applied as usual. Otherwise, $u_j$ will be redefined as $\frac{u_j}{2}$, and the other half 
+   (to be applied at the end) will be defined using vectors $\frac{u_{j'}}{2}$ and $v_{j'}^T=v_{j'}^T$.
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:48]:
```suggestion
   the update is applied as usual. Otherwise, the current update $u_j$ will be redefined as $\frac{u_j}{2}$. The missing half-update will be delayed to the end of the algorithm; it is stored in the waiting-queue `later_updates`.
```

File: org/qmckl_sherman_morrison_woodbury.org [hunk 6]
```diff
@@ -0,0 +1,1775 @@
...
+   | double   | breakdown                      | in    | Break-down parameter on which to fail or not                  |
+   | double   | Slater_inv[Dim*Dim]            | inout | Array containing the inverse Slater-matrix                    |
+   | double   | later_updates[Dim * N_updates] | inout | Array containing the split updates for later                  |
+   | uint64_t | later_index[N_updates]         | inout | Array containing the positions of the split updates for later |
+   | uint64_t | later                          | inout | Number of split updates for later                             |
+  
+
+*** Requirements
+
+    - ~Dim >= 2~
```
Comment (fmgjcoppens) [inline org/qmckl_sherman_morrison_woodbury.org:64]: Expres in terms of element, not in bytes. Also Updates is not multiplied by N_updates! 
 ** Change for all following kernels.

File: org/qmckl_sherman_morrison_woodbury.org [hunk 7]
```diff
@@ -0,0 +1,1775 @@
...
+    for (uint64_t i = 0; i < Dim; i++) {
+      C[i] = 0;
+      for (uint64_t j = 0; j < Dim; j++) {
+        C[i] += Slater_inv[i * Dim + j] * Updates[l * Dim + j];
+      }
+    }
+
+    // Denominator
+    double den = 1 + C[Updates_index[l] - 1];
+    if (fabs(den) < breakdown) {
```
Comment (fmgjcoppens) [inline org/qmckl_sherman_morrison_woodbury.org:130]: Add comment explaining this block (split)

File: org/qmckl_sherman_morrison_woodbury.org [hunk 8]
```diff
@@ -0,0 +1,1775 @@
...
+   :PROPERTIES:
+   :Name:     qmckl_sherman_morrison
+   :CRetType: qmckl_exit_code
+   :FRetType: qmckl_exit_code
+   :END:
+
+   This is the simplest of the available Sherman-Morrison-Woodbury
+   kernels. It applies rank-1 updates one by one in the order
+   that is given. It only checks if the denominator in the
+   Sherman-Morrison formula is not too close to zero when an update is evaluated.
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:215]: Specify "too close to zero".

File: org/qmckl_sherman_morrison_woodbury.org [hunk 9]
```diff
@@ -0,0 +1,1775 @@
...
+   It will exit with an error code of the denominator is too close to zero.
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:216]:
```suggestion
   It will exit with an error code when the denominator is too close to zero.
```

File: org/qmckl_sherman_morrison_woodbury.org [hunk 10]
```diff
@@ -0,0 +1,1775 @@
...
+
+   The formula that is applied is
+   \[
+    (S + uv^T)^{-1} = S^{-1} - \frac{S^{-1} uv^T S^{-1}}{1 + v^T S^{-1} u}
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:220]: Check that notations are uniform across the whole document.

File: org/qmckl_sherman_morrison_woodbury.org (hunk 6 above)
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:64]: Can we also add an 
```c
assert(Dim >= 2);
```
at the beginning of the code.

File: org/qmckl_sherman_morrison_woodbury.org [hunk 11]
```diff
@@ -0,0 +1,1775 @@
...
+  }
+
+  return QMCKL_SUCCESS;
+}
+
+    #+end_src
+    
+*** Performance
+
+This function performce better for cycles with 1 rank-1 update and with a high fail-rate.
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:166]: Check and eventually update the performance recommendations following new report.

File: org/qmckl_sherman_morrison_woodbury.org [hunk 12]
```diff
@@ -0,0 +1,1775 @@
...
+for (unsigned int i = 0; i < Dim; i++) {
+  for (unsigned int j = 0; j < Dim; j++) {
+    if (i == j && fabs(res[i * Dim + j] - 1) > tolerance) {
+      rc = QMCKL_FAILURE;
+    }
+    if (i != j && fabs(res[i * Dim + j]) > tolerance) {
+      rc = QMCKL_FAILURE;
+    }
+  }
+}
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:458]: Once PR #27 is merged, please add a `vfc_probe` here that check significant digits of Frobenius norm.

File: org/qmckl_sherman_morrison_woodbury.org [hunk 13]
```diff
@@ -0,0 +1,1775 @@
...
+   :FRetType: qmckl_exit_code
+   :END:
+
+   This is a variation on the 'Naive' Sherman-Morrison kernel. Whenever the denominator $1+v_j^T S^{-1} u_j$ in
+   the Sherman-Morrison formula is deemed to be too close to zero, the update $u_j$ is split in half:
+   $u_j \rightarrow \frac{1}{1} u_j$. One half is applied immediately --necessarily increasing the value of the
+   denominator because of the split-- while the other halve is put in a queue that will be applied when all the
+   remaining updates have been treated. The kernel is executed recursively until the queue is eiter empty and all
+   updates are applied successfully, or the size of the queue equals the number of initial updates. In the last
+   case the Slater-matrix that would have resulted from applying the updates is un-invertable and therefore the
```
Comment (pablooliveira) [inline org/qmckl_sherman_morrison_woodbury.org:950]:
```suggestion
   case the Slater-matrix that would have resulted from applying the updates is singular and therefore the
```

**Review by pablooliveira — CHANGES_REQUESTED** [review]

File: org/qmckl_sherman_morrison_woodbury.org [hunk 14]
```diff
@@ -0,0 +1,1775 @@
...
+
+int main() {
+  qmckl_context context;
+  context = qmckl_context_create();
+
+  qmckl_exit_code rc;
+  #+end_src
+
+  
+* Helper Functions
```
[the remark this answers is not in the document]
Comment (fmgjcoppens) [reply org/qmckl_sherman_morrison_woodbury.org:30]: This does not seem possible. The code is generated in such way that moving the header part down makes the code not compile.

File: Makefile.am [hunk 15]
```diff
@@ -58,6 +58,7 @@ fortrandir = $(datadir)/$(PACKAGE_NAME)/fortran/
 dist_fortran_DATA = $(qmckl_f)
 
 AM_CPPFLAGS = -I$(srcdir)/src -I$(srcdir)/include
+AM_FCFLAGS = -fno-underscoring
```
[the remark this answers is not in the document]
Comment (fmgjcoppens) [reply Makefile.am:61]: Vijay is checking this...

[the remark this answers is not in the document]
Comment (v1j4y) [reply Makefile.am:61]: Hi @pablooliveira I'm looking into this and will remove it if it is not needed ASAP.

File: org/qmckl_sherman_morrison_woodbury.org (hunk 12 above)
Comment (v1j4y) [reply org/qmckl_sherman_morrison_woodbury.org:296]: @fmgjcoppens Can you please add a TODO here so that we don't forget ?

File: Makefile.am (hunk 15 above)
[the remark this answers is not in the document]
Comment (pablooliveira) [reply Makefile.am:61]: Thanks for looking into this @v1j4y .After discussing with @fmgjcoppens we believe it can be removed safely. So we are going to proceed with removal. If you later feel it need to be added back, we'll do that !

**Review by pablooliveira — APPROVED** [review]
LGTM :tada: 

With two minor requests:
- remove `-fno-underscoring`
- add asserts

File: Makefile.am (hunk 15 above)
[the remark this answers is not in the document]
Comment (fmgjcoppens) [reply Makefile.am:61]: I will remove it for now and merge the PR since we need SMW tomorrow to start testing it in QMC=Chem. 

If it turns out we need it we can put it back.

**Comment by pablooliveira** [comment]
I think the failure of tests in 6cc5b1a :
```
[...]
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_slagel_splitting_c_'
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_sherman_morrison_splitting_c_'
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_sherman_morrison_c_'
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_sherman_morrison_smw32s_c_'
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_woodbury_3_c_'
/usr/bin/ld: src/.libs/libqmckl.so: undefined reference to `qmckl_woodbury_2_c_'
```

is linked to the option `-fno-underscoring` we removed. So it seems it is currently needed to build the fortran to c interface. Either we add back the option or we must find a way to modify the interface so it deals with the underscore.
